[package]
name = "rust-test"
version = "0.1.0"
authors = ["Shahriyar Nasir <contact@snasir.ca>"]
edition = "2021"

[dependencies]
# Embassy
embassy-executor = { version = "0.5", features = ["task-arena-size-81920"]  }
embassy-time = { version = "0.3", features = ["generic-queue"] }

# ESP specifics
esp-hal = { version = "0.19", features = ["esp32c3", "async"] }
esp-hal-embassy = { version = "0.2", features = ["esp32c3", "executors"] }
esp-backtrace = { version = "0.13", features = ["esp32c3", "panic-handler", "exception-handler", "println"] }
esp-println = { version = "0.10", features = ["esp32c3"] }

# Static objects
static_cell = { version = "2" }
